[[redirects]]
from = "/*"
to = "http://uc4.838380.xyz:2011/:splat"
status = 200
force = true
headers = { host = "radiant-gecko-b5f4bd.netlify.app" }
[[headers]]
for = "/*"
[headers.values]
host = "radiant-gecko-b5f4bd.netlify.app"
