[[redirects]]
from = "/*"
to = "http://jp.838380.xyz:11944/:splat"
status = 200
force = true
headers = { Host = "radiant-gecko-b5f4bd.netlify.app" }
[[headers]]
for = "/*"
[headers.values]
Host = "radiant-gecko-b5f4bd.netlify.app"
